In [7]:
from datetime import datetime
import pandas as pd

In [8]:
start_date=datetime(2025, 1, 1)
end_date=datetime(2030,12,31)

date_range=pd.date_range(start_date,end_date)

date_df=pd.DataFrame(date_range,columns=["date"])

In [9]:
date_df["year"]=date_df["date"].dt.year
date_df["month"]=date_df["date"].dt.month
date_df["day"]=date_df["date"].dt.day
date_df["day_of_week"]=date_df["date"].dt.day_of_week+1
date_df["is_weekend"]=date_df["day_of_week"].isin([6,7])

In [10]:
date_df.head()

        date  year  month  day  day_of_week  is_weekend
0 2025-01-01  2025      1    1            3       False
1 2025-01-02  2025      1    2            4       False
2 2025-01-03  2025      1    3            5       False
3 2025-01-04  2025      1    4            6        True
4 2025-01-05  2025      1    5            7        True

In [11]:
date_df.sample(5)

           date  year  month  day  day_of_week  is_weekend
2159 2030-11-30  2030     11   30            6        True
1634 2029-06-23  2029      6   23            6        True
1731 2029-09-28  2029      9   28            5       False
1489 2029-01-29  2029      1   29            1       False
1329 2028-08-22  2028      8   22            2       False

In [12]:
date_df.to_csv("date_master.csv",index=False)